from .mask_node import NODE_CLASS_MAPPINGS as COLORMASK_NODE_CLASS_MAPPINGS
from .mask_node import NODE_DISPLAY_NAME_MAPPINGS as COLORMASK_NODE_DISPLAY_NAME_MAPPINGS
from .caption_folder_node import NODE_CLASS_MAPPINGS as CAPTION_NODE_CLASS_MAPPINGS
from .caption_folder_node import NODE_DISPLAY_NAME_MAPPINGS as CAPTION_NODE_DISPLAY_NAME_MAPPINGS
from .save_prompt_as_batch_node import NODE_CLASS_MAPPINGS as SAVE_PROMPT_AS_BATCH_NODE_CLASS_MAPPINGS
from .save_prompt_as_batch_node import NODE_DISPLAY_NAME_MAPPINGS as SAVE_PROMPT_AS_BATCH_NODE_DISPLAY_NAME_MAPPINGS

# Merge the dictionaries
NODE_CLASS_MAPPINGS = {**COLORMASK_NODE_CLASS_MAPPINGS, **CAPTION_NODE_CLASS_MAPPINGS, **SAVE_PROMPT_AS_BATCH_NODE_CLASS_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**COLORMASK_NODE_DISPLAY_NAME_MAPPINGS, **CAPTION_NODE_DISPLAY_NAME_MAPPINGS, **SAVE_PROMPT_AS_BATCH_NODE_DISPLAY_NAME_MAPPINGS}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']